### ISSUE TITLE
Accent typo

### ISSUE THREAD

**Issue by danielmarschall** [frdl/frdl-oidplus-wtf-plugin#1]
https://github.com/frdl/frdl-oidplus-wtf-plugin/blob/fc93ddbabb2474fc3ec09fe06e41e49b9f102d08/plugin.php#L133

I think there is a typo. You probably mean e without accent.

**Comment by wehowski** [comment]
**Thank you!**
Fixed.

**Comment by wehowski** [comment]
closed.
